baseURL      = "https://nguyenhuythanh.com/"
theme        = "hugo-bearblog"
paginate     = 10
rssLimit     = 10
enableGitInfo = true

# Basic metadata configuration for your blog.
title = "Thanh's Islet ğŸï¸"
copyright = "Copyright Â© 2024, Thanh Nguyen."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
# [permalinks]
#   blog = "/:slug/"
#   tags = "/blog/:slug"

# PygmentsCodeFences = true
# PygmentsStyle = "monokai"

[author]
  name = "Thanh Nguyen"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  dateform        = "2006-01-02"
  dateformShort   = "01-02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "\"islet\" means a small island ğŸï¸"

  disableReadOtherPosts = true
  enableThemeToggle = true

  [params.footer]
    trademark = true
    rss = true
    author = true

  [params.logo]
    logoText     = "islet"
    logoHomeLink = "/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/thanhnguyen2187"

  [[params.social]]
    name = "email"
    url  = "mailto:thanhnguyen2187@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nguyen-huy-thanh/"

[taxonomies]
  category = "categories"
  tag      = "tags"
  series   = "series"

[menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name       = "About"
  #   url        = "/about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
